apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: registration
  namespace: {{ include "registration.namespace" . }}
  labels:
    app: registration
    version: {{ .Values.image.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: "registration-service:{{ .Values.image.tag }}"
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb.mongodb.svc.cluster.local
            - name: SUMMARY_HOST
              value: summary
            - name: SUMMARY_PORT
              value: "8081"
            #- name: SPRING_DATA_MONGODB_USERNAME
            #  value: admin
            #- name: SPRING_DATA_MONGODB_PASSWORD
            #  value: admin
          ports:
            - containerPort: 8080