apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: registration
  namespace: {{ include "registration.namespace" . }}
  labels:
    app: registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: registration-service:0.1.0-dev.4.uncommitted_8754f5d
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb.mongodb.svc.cluster.local
            - name: SPRING_DATA_MONGODB_USERNAME
              value: admin
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: admin
          ports:
            - containerPort: 8080