apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: summary
  namespace: {{ include "registration.namespace" . }}
  labels:
    version: {{ .Values.image.tag }}
    app: summary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary
  template:
    metadata:
      labels:
        app: summary
    spec:
      containers:
        - name: summary
          image: "summary-service:{{ .Values.image.tag }}"
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb.mongodb.svc.cluster.local
          envFrom:
            - secretRef:
                name: mongodb-summary
          ports:
            - containerPort: 8081