apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: summary
    app.kubernetes.io/instance: example-app
  name: summary
  namespace: {{ include "summary.namespace" . }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: summary
status:
  loadBalancer: {}